print("              ffffffffffffffff")
print("            ff                ff")
print("          ff                    ff")
print("        ff                        ff")
print("       ff       ff        ff       ff")
print("      ff        ff        ff        ff")
print("     ff                              ff")
print("    ff                                ff")
print("   ff                                  ff")
print("   ff        ff             ff         ff")
print("    ff         ff         ff          ff")
print("     ff          ff     ff           ff")
print("      ff           fffff            ff")
print("       ff                          ff")
print("         ff                      ff")
print("           ff                  ff")
print("             ff              ff")
print("              ffffffffffffffff")

