print ("*" * 10, "README", "*" * 10)
print("Enter values ​​with a dot if you enter non-integer numbers!!!")
print()
print ("*" * 10, "WEIGHT", "*" * 10)
weight_gr = float(input ("Input weight in grams: "))
print ("Weight in grams: ",weight_gr,"gr")
print ("Weight in kilograms: " ,weight_gr * 0.001,"kg")
print ("Weight in ton: " ,weight_gr * (0.001 ** 2),"t")
print()
print ("*" * 10, "MEMORY", "*" * 10)
memory_byte = float(input ("Input memory in bytes: "))
print ("Memory in bytes: ",memory_byte,"byte")
print ("Memory in kilobytes: " ,memory_byte * 0.0009765625,"kb")
print ("Memory in megabytes: " ,memory_byte * (0.0009765625 ** 2),"mb")
print()
print ("*" * 10, "TWO NUMBERS EXCHANGE", "*" * 10)
first_number = input("Input first number: ")
second_number = input("Input second number: ")
print("First number: ",first_number)
print("Second number: ",second_number)
print()
print ("*" * 10, "EXCHANGE", "*" * 10)
first_number , second_number = second_number , first_number
print("First number: ",first_number)
print("Second number: ",second_number)
print()
print ("*" * 10, "RECTANGLE SQUARE AND PERIMETER", "*" * 10)
rectangle_lenght = float(input("Input rectangle lenght(cm): " ))
rectangle_width = float(input("Input rectangle width(cm): "))
print("Square of rectangle: ",rectangle_lenght * rectangle_width)
print("Perimeter of rectangle: ",(rectangle_lenght + rectangle_width) * 2)
print()
print ("*" * 10, "CIRCLE", "*" * 10)
from math import pi
circle_radius = float(input("Input circle radius(cm): "))
print("Square of circle: ",pi * (circle_radius ** 2))
print("Perimeter of circle: ",2 * pi * circle_radius)
print()
print ("*" * 10, "TRIANGLE", "*" * 10)
triangle_leg1 = float(input("Input triangle Leg1(cm): "))
triangle_leg2 = float(input("Input triangle Leg2(cm): "))
triangle_hypotenuse = triangle_leg1**2+triangle_leg2**2
triangle_hypotenuse = triangle_hypotenuse**(1./2)
print("Hypotenuse of triangle(cm): ",triangle_hypotenuse)

